### ISSUE TITLE
Errors since last week

### ISSUE THREAD

**Issue by DAVIZINH0** [bierdok/gnotify#5]
Hello,
I use gnotify in a docker installation and allways works great, but recently it stop working

this is the error:

root@domoticz-oficial:/opt/domoticz/scripts/personales/GHome# gnotify -H 192.168.1.122 -l es Atencion     
                             
Traceback (most recent call last):                                                                                                     
  File "/usr/local/bin/gnotify", line 8, in <module>                                                                                   
    sys.exit(main())                                                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/gnotify/gnotify.py", line 58, in main                                                   
    from pychromecast import Chromecast                                                                                                
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/__init__.py", line 11, in <module>                                         
    from . import socket_client                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/socket_client.py", line 23, in <module>                                    
    from . import cast_channel_pb2                                                                                                     
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/cast_channel_pb2.py", line 36, in <module>                                 
    type=None),                                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py", line 755, in __new__                                    
    _message.Message._CheckCalledFromGeneratedFile()                                                                                   
TypeError: Descriptors cannot not be created directly.                                                                                 
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.               
If you cannot immediately regenerate your protos, some other possible workarounds are:                                                 
 1. Downgrade the protobuf package to 3.20.x or lower.                                                                                 
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).                 
                                                                                                                                       
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by DAVIZINH0** [comment]
i solved the problem. I think the problem is protobuf, because gnotify uses a old version and with a upgrade of the protobuf library, gnotify crash

i solve the problem with this workarround:
pip uninstall protobuf
and then i install a old version with:
pip install protobuf==3.20
